/**
 * Cell grid enforcement for the log view.
 *
 * The backend lays the log out with rich (`module/webui/api/helpers.py::render_log`
 * prints renderables at a fixed console width), so every box border and table
 * column in the browser has to land on the cell grid *rich* counted - not on
 * whatever advance width the browser's font fallback gives a glyph.
 *
 * Measured on Windows (Consolas + Microsoft YaHei fallback, 0.85rem log font):
 *
 *   char class                       rich   browser   per-char error
 *   Latin / digits / space / box     1      1.000     0
 *   CJK, kana, fullwidth forms        2      1.871     -0.13  (drifts left)
 *   U+2600..U+2BFF symbols, emoji     1      1.1-2.50  +0.1..+1.5 (drifts right)
 *
 * A traceback line with 12 CJK characters therefore lost ~1.6 cells: exactly
 * the "right edge of the error box does not line up" symptom, and it grew with
 * the number of errors on screen.
 *
 * The fix has two halves, and both are needed:
 *   1. the *target* width comes from rich's own table (`cell-widths.json`,
 *      generated by dev_tools/gen_log_cell_widths.py) - never from the font;
 *   2. whether a character needs a pin at all is decided by measuring the
 *      browser once per code point and caching the result, so the rule
 *      self-corrects on other machines, font stacks and zoom levels instead of
 *      hard-coding "CJK is 2 cells" (which is only true for a CJK *monospace*
 *      font, and Windows ships none).
 */

import widths from "./cell-widths.json";

type Range = [number, number];

const WIDE: Range[] = widths.wide as Range[];
const ZERO: Range[] = widths.zero as Range[];

/** Cell count rich assumed for `cp` (0, 1 or 2). */
export function cellWidth(cp: number): 0 | 1 | 2 {
  if (inRanges(ZERO, cp)) return 0;
  if (inRanges(WIDE, cp)) return 2;
  return 1;
}

function inRanges(ranges: Range[], cp: number): boolean {
  let lo = 0;
  let hi = ranges.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const range = ranges[mid];
    if (cp < range[0]) hi = mid - 1;
    else if (cp > range[1]) lo = mid + 1;
    else return true;
  }
  return false;
}

/**
 * Measured natural advance per code point, in cells. `null` = not measured yet.
 * Measurement needs a host element that inherits the log font; without one
 * (unit tests, SSR) we fall back to pinning every non-1-cell character, which
 * is the safe direction: over-pinning only costs a span, under-pinning
 * misaligns the grid.
 */
const natural = new Map<number, number>();
let cellPx = 0;
let chPx = 0;
let host: HTMLElement | null = null;

/** Test hook: forget every cached measurement. */
export function resetCellCache(): void {
  natural.clear();
  cellPx = 0;
  chPx = 0;
  host = null;
}
/**
 * Attach the element used for measurements. It must carry the log typography
 * (`.alas-log`), because the answer depends on the resolved font. Passing a
 * different element invalidates the cache.
 */
export function setMeasureHost(el: HTMLElement | null): void {
  if (el !== host) {
    host = el;
    natural.clear();
    cellPx = 0;
    chPx = 0;
  }
}

function measure(): boolean {
  if (!host) return false;
  if (cellPx > 0) return true;
  const probe = document.createElement("span");
  probe.style.cssText = "position:absolute;visibility:hidden;left:-99999px;white-space:pre;";
  host.appendChild(probe);
  probe.textContent = "M".repeat(32);
  cellPx = probe.getBoundingClientRect().width / 32;
  probe.textContent = "";
  const ch = document.createElement("span");
  ch.style.cssText = "display:inline-block;width:1ch;";
  probe.appendChild(ch);
  chPx = ch.getBoundingClientRect().width;
  probe.remove();
  // A hidden/undisplayed host measures 0; treat that as "cannot measure".
  return cellPx > 0 && chPx > 0;
}

/** Measure the not-yet-known code points in `text` (one layout flush). */
export function learnCells(text: string): void {
  if (!measure()) return;
  const pending: number[] = [];
  const seen = new Set<number>();
  for (const ch of text) {
    const cp = ch.codePointAt(0)!;
    if (seen.has(cp)) continue;
    // Control characters and combining marks are never worth measuring.
    if (cellWidth(cp) === 0) {
      seen.add(cp);
      natural.set(cp, 0);
      continue;
    }
    seen.add(cp);
    pending.push(cp);
  }
  if (pending.length === 0) return;

  const probe = document.createElement("span");
  probe.style.cssText = "position:absolute;visibility:hidden;left:-99999px;white-space:pre;";
  const spans = pending.map((cp) => {
    const span = document.createElement("span");
    span.textContent = String.fromCodePoint(cp);
    probe.appendChild(span);
    return span;
  });
  host!.appendChild(probe);
  for (let i = 0; i < pending.length; i++) {
    natural.set(pending[i], spans[i].getBoundingClientRect().width / cellPx);
  }
  probe.remove();
}

/** Does `ch` have to be forced into a box to match rich's grid? */
function needsPin(ch: string): 0 | 1 | 2 {
  const cp = ch.codePointAt(0)!;
  const target = cellWidth(cp);
  if (target === 0) return 0;
  const known = natural.get(cp);
  if (known === undefined) {
    // Not measured (no host / not learned yet): pin exactly the characters
    // rich already knows are wide, and leave everything else to the font.
    return target === 2 ? 2 : 0;
  }
  return Math.abs(known - target) > 0.02 ? target : 0;
}

const escapeMap: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
};

export function escapeHtml(text: string): string {
  return text.replace(/[&<>]/g, (c) => escapeMap[c]);
}

/**
 * Wrap characters whose natural advance disagrees with rich's grid into
 * fixed-width inline boxes, so the following glyphs (box borders, padding)
 * land where rich put them.
 *
 * Consecutive characters that need the same width share one box: a 12-character
 * Chinese run costs one span, not twelve. That matters because the log view
 * re-renders on every SSE batch; the previous per-character version was gated
 * to box-drawing lines only, which is precisely why plain error lines with
 * Chinese text stayed misaligned.
 */
export function pinCells(escaped: string): string {
  let out = "";
  let run = "";
  let runPin = 0; // per-character pin width (0 = unpinned)
  let runCells = 0; // accumulated box width, in cells

  const flush = () => {
    if (!run) return;
    out += runPin === 0 ? run : `<span class="cell-pin" style="width:${runCells}ch">${run}</span>`;
    run = "";
    runPin = 0;
    runCells = 0;
  };

  for (const ch of escaped) {
    const pin = needsPin(ch);
    if (pin === 0) {
      flush();
      out += ch;
    } else {
      if (runPin !== pin) flush();
      run += ch;
      runPin = pin;
      runCells += pin;
    }
  }
  flush();
  return out;
}
